#!/usr/bin/env spang2
# @endpoint orthodev
# @option -ac --time
# @param idref=affyProbeset
# @param level=over

SELECT DISTINCT ?gene ?tissue ?label_ja ?label
WHERE {
  ?gene refexo:{{idref}} ?seq .
  ?seq refexo:{{level}}ExpressedIn ?tissue .
  ?tissue rdfs:label ?label_ja .
  FILTER(lang(?label_ja) = 'ja')
  ?tissue skos:prefLabel ?label .
}
