#!/usr/bin/env spang2
# @endpoint orthodev
# @option -ac
SELECT *
WHERE {
  ncbigene:7849 ?xref ?s .
  ?s ?pred ?tissue .
  ?tissue skos:prefLabel ?label .
  VALUES (?pred) { (refexo:isPositivelySpecificTo) (refexo:isNegativelySpecificTo) }
  VALUES (?xref) { (refexo:affyProbeset) (refexo:refseq) }  
}
