#!/usr/bin/env spang2
# @endpoint https://orth.dbcls.jp/sparql-dev
# @option -a
# @param specific_tissue=v24_40

PREFIX refexo: <http://purl.jp/bio/01/refexo#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT(COUNT(DISTINCT ?upstream) AS ?upstream_count) ?gene
WHERE {
  ?upstream refexo:ensembl/obo:RO_0002428/refexo:ncbigene ?gene .
  {
    SELECT DISTINCT ?gene (GROUP_CONCAT(DISTINCT ?tissue; separator=",") AS ?tissues)
    WHERE {
      ?gene refexo:affyProbeset/refexo:isPositivelySpecificTo refexo:{{specific_tissue}} , ?tissue .
    }
  }
  FILTER (?tissues = str(refexo:{{specific_tissue}}))
}
ORDER BY DESC(?upstream_count)
