#!/usr/bin/env spang2
# @endpoint orthodev
# @option -a --time
PREFIX refexo: <http://purl.jp/bio/01/refexo#>

SELECT DISTINCT ?gene
WHERE {
  ?gene refexo:affyProbeset ?affy .
  ?affy refexo:isPositivelySpecificTo refexo:v32_40 .
}
