#!/usr/bin/env spang2
# @endpoint orthodev
# @option -a
# @param specific_tissue=v24_40

SELECT ?gene
WHERE {
  {
    SELECT DISTINCT ?gene (GROUP_CONCAT(DISTINCT ?tissue; separator=",") AS ?tissues)
    WHERE {
      ?gene refexo:affyProbeset/refexo:isPositivelySpecificTo refexo:{{specific_tissue}} , ?tissue .
    }
  }
  FILTER (?tissues = str(refexo:{{specific_tissue}}))
}
